default: &default
  adapter: postgis
  pool: 5
  timeout: 5000
  user: treasure_hunt
  password: treasure_hunt

development:
  <<: *default
  database: treasure_hunt_dev

test:
  <<: *default
  database: treasure_hunt_test
